services:
  # Web service configuration(Django API application)
  - type: web
    name: crypto-portfolio-api
    env: python
    region: oregon
    plan: free
    branch: main
    rootDirectory: crypto_api_project

    # Commands to set up and start the Django application
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn crypto_api_project.wsgi:application

    # Environment groups for managing environment variables
    envGroups:
      - crypto-portfolio-env-group

    # Environment variables specific to this service
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "crypto-portfolio-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-portfolio-db
          property: connectionString

  # PostgreSQL database service configuration
  - type: pserv
    name: crypto-portfolio-db
    env: docker
    plan: free
    region: oregon
    dockerCommand: postgres

    disks:
      - name: postgres-data
        mountPath: /var/lib/postgresql/data
        sizeGB: 1

    # Database configuration
    envVars:
      - key: POSTGRES_DB
        value: crypto_portfolio_db  
      - key: POSTGRES_USER
        value: crypto_user
      - key: POSTGRES_PASSWORD
        generateValue=: true
        length: 16




    