services:
  # Web service configuration(Django API application)
  - type: web
    name: crypto-portfolio-api
    env: python
    region: oregon
    plan: free
    branch: main

    # Commands to set up and start the Django application
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd crypto_api_project
      python manage.py collectstatic --no-input
      python manage.py migrate --no-input
    startCommand: cd crypto_api_project && gunicorn crypto_api_project.wsgi:application


    # Environment variables specific to this service
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - fromGroup: crypto-portfolio-env-group

  



    